############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/services/"
weight = 2

[[main]]
name = "Case Studies"
url = "/case-studies/"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Testimonials"
url = "/#testimonials"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6


# footer menu
[[footer]]
name = "Services"
url = "/services/"
weight = 1

[[footer]]
name = "AI Agent Services"
url = "/services/ai-agent-services/"
weight = 2

[[footer]]
name = "Case Studies"
url = "/case-studies/"
weight = 3

[[footer]]
name = "Blog"
url = "/blog"
weight = 4

[[footer]]
name = "Contact"
url = "/contact"
weight = 5

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 6
